name = "chat-gpt-api"
main = "_worker.js"
compatibility_date = "2024-12-18"

# Cloudflare Pages configuration
[env.production]
name = "chat-gpt-api"

[env.staging]
name = "chat-gpt-api-staging"

# For Cloudflare Pages, we don't need routes configuration
# The _worker.js file will handle the routing